### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by tudor-ghiorghiu** [pokusew/node-pcsclite#16]
Hey! First of all thanks for the effort on creating this library!

I was wondering, are you are thinking of offering react-native support also, at least for Android?

**Comment by Psychopoulet** [comment]
there is already typescript definition

**Comment by pokusew** [comment]
Hi @tudor-ghiorghiu, 

thank you for posting your issue here. 🙂

Unfortunately, the **mobile support is virtually impossible**. 🙁

pcsclite uses **Node Native Modules** to access system **PC/SC API**.
So the **Node.js runtime and PC/SC API are required** for pcsclite to run. That makes it possible to use it on the most of OS (Windows, macOS, Linux) directly in Node.js or in Electron.js and NW.js desktop apps. On the other hand, these requirements are not normally met on mobile devices. On top of that, React Native does not contain any Node.js runtime.

**Hope I clarified a few things a bit.** 🙂

cc @Psychopoulet

**Comment by Psychopoulet** [comment]
ow. It's far more than only code definitions, so... ><
thanks for the answer, @pokusew, I didn't see that comming !
